name: ESLint Check

on:
  push:
    branches:
      - main
      - develop
      - devops-workflow
  pull_request:
    branches:
      - main
      - develop
      - devops-workflow

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npx eslint . --ext .ts,.js --format json -o eslint-report.json
      env:
        NODE_ENV: development

    - name: Format ESLint report to SARIF
      run: npx eslint-formatter-sarif -o eslint-results.sarif eslint-report.json

    - name: Upload ESLint SARIF results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: eslint-results.sarif

    - name: Archive ESLint Report
      uses: actions/upload-artifact@v3
      with:
        name: eslint-report
        path: eslint-report.json
